#!/usr/bin/env bash
# measure.sh - loop-spec adoption count (derived, no metered API).
#
# Counts the live loop specifications in the canonical loops directory. The count
# is real-usage evidence: the loop contract is not a hypothesis, it governs this
# many scheduled jobs in production. The number is derived here, never hand-typed,
# so it cannot drift away from reality.
#
#   bash measure.sh            # regenerate results.md and print the count
#   bash measure.sh --print    # print the summary only, do not write results.md
#
# The committed results.md is exactly this script's output, so it regenerates
# while the loops directory is unchanged.

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STANDARDS_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
REPO_ROOT="$(cd "$STANDARDS_DIR/.." && pwd)"
RESULTS="$SCRIPT_DIR/results.md"

# Resolve the canonical loops directory. The Mini canonical keeps loop specs at
# compound-ai/loops/ (the live tree) or loops/ (the sandbox copy). Probe both.
LOOPS_DIR=""
for cand in "$REPO_ROOT/compound-ai/loops" "$REPO_ROOT/loops" "$STANDARDS_DIR/loops"; do
  if [ -d "$cand" ]; then LOOPS_DIR="$cand"; break; fi
done

if [ -z "$LOOPS_DIR" ]; then
  echo "loop-adoption: no loops directory found (looked under compound-ai/loops, loops)" >&2
  exit 2
fi

# A loop spec is a *.spec.md file in the loops directory.
spec_files() { find "$LOOPS_DIR" -maxdepth 1 -type f -name '*.spec.md' -print | sort; }

COUNT=$(spec_files | grep -c .)
LOOPS_REL="${LOOPS_DIR#$REPO_ROOT/}"

render() {
  cat <<EOF
# Loop-adoption evidence

Generated by \`measure.sh\`. No metered API. Re-run \`bash measure.sh\` to
regenerate this file from the live loops directory.

## Count

**${COUNT}** live loop specifications in \`${LOOPS_REL}/\`.

This is the evidence against "unproven": the goal-and-loop contract is in real,
scheduled production use at this scale, not a single-example hypothesis. Public
adoption is early; internal usage is real and measurable. The count is derived
by this script, so it stays honest and cannot drift from the files on disk.

## Live loop specifications

The individual spec filenames are internal and withheld here: the proof is the
derived count above and its method, not the names. The count is whatever the
canonical loops directory reports, so it cannot drift from the files on disk.

## Method

\`find\` for \`*.spec.md\` in the canonical loops directory, then count. Pure
shell, no network, no API key. The number above is whatever the files report.
EOF
}

if [ "${1:-}" = "--print" ]; then
  render
else
  render > "$RESULTS"
  printf 'loop-adoption: %s live loop specs in %s\n' "$COUNT" "$LOOPS_REL"
  printf 'wrote %s\n' "${RESULTS#$STANDARDS_DIR/}"
fi
